# Generated by Django 4.2.4 on 2023-08-05 15:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('question', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2023, 8, 5, 15, 15, 12, 572121, tzinfo=datetime.timezone.utc))),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quetion_user', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anwser', models.TextField(max_length=200)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2023, 8, 5, 15, 15, 12, 572714, tzinfo=datetime.timezone.utc))),
                ('Quetion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='question_app.questions')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
