# Generated by Django 4.2.4 on 2023-08-05 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 15, 16, 34, 235838, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 15, 16, 34, 235325, tzinfo=datetime.timezone.utc)),
        ),
    ]
