# Generated by Django 4.2.4 on 2023-08-12 17:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_app', '0005_alter_answers_create_at_alter_questions_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 17, 10, 0, 962008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questions',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 17, 10, 0, 961498, tzinfo=datetime.timezone.utc)),
        ),
    ]
